// FAKE DATA
export const books = [
  {
    id: 1,
    title: "Premium Coffee Flavoured Gift Pack ",
    url: "https://m.media-amazon.com/images/I/71QzeARjLpL._SX679_.jpg",
    originalPrice: 49.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Ferrero Rocher Chocolates, 300g [Pack of 4, 24 Pieces]",
    url: "https://m.media-amazon.com/images/I/71T47+a3VAL._SX679_PIbundle-24,TopRight,0,0_SX679SY566SH20_.jpg",
    originalPrice: 39,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "ADISA women girls embroided sling bag",
    url: "https://m.media-amazon.com/images/I/91o7FLujlML._SL1500_.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Kimirica Love Story Luxury Bath and Body Care Gift Set Box | Bath Salt, Body Wash, Body Lotion, Bathing Bar and Hand cream | Pack of 5 | For Men and Women | Pampering Kit for Birthday ,Anniversary & All Special Occasions | Premium Gift Packaging 100% Vegan",
    url: "https://m.media-amazon.com/images/I/51MWkSY171L._SX522_.jpg",
    originalPrice: 44,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "Galaxy Hi-Tech® Pioneer Bot Robot Colorful Lights and Music | All Direction Movement Dancing Robot Toys for Boys and Girls Multi-Colour",
    url: "https://m.media-amazon.com/images/I/41dPr1Tlc+L._SY300_SX300_.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "SClara Pure 925 Sterling Silver Minimal Office wear Finger Ring with Adjustable Band | Valentine Gift for Women Girls Wife Girlfriend | Multiple Design Options",
    url: "https://m.media-amazon.com/images/I/51kJTUwqw9L._SL1280_.jpg",
    originalPrice: 70,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "TIED RIBBONS Birthday Gift / Printed Cushion Cover With Filler (12 X 12 Inch) And Coffee Mug Cup(satin & Microfiber)",
    url: "https://m.media-amazon.com/images/I/51r6y+6glML._SX300_SY300_.jpg",
    originalPrice: 11,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "SWADESI STUFF Wooden Wall Hanging Heart Shape Photo Frame Collage (Set of 31, Black)",
    url: "https://m.media-amazon.com/images/I/81V09kn7kGL._SX679_.jpg",
    originalPrice: 38,
    salePrice: 17.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Art Street Photo Frame For Wall Set Wall Hanging Photo Frame For Home and Office Decoration (Brown New)48 Laws of Power Summary",
    url: "https://m.media-amazon.com/images/I/31xXLQrgkaL._SX300_SY300_QL70_FMwebp_.jpg",
    originalPrice: 35,
    salePrice: 19.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "KYARI Radiant Multicolour Metal Pot with Stand, Rust-Free Powder Coating, Indoor Outdoor Use, Home Office Decor, Plants Not Included, Pot Size: 10 * 13cm, Stand Height: 7.5cm",
    url: "https://m.media-amazon.com/images/I/81ETAsFQGyL._SX679_.jpg",
    originalPrice: 40,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "DearJoy Polyester Big Size Fibre Filled Stuffed Animal Elephant Soft Toy For Baby Of Plush Hugging Pillow Soft Toy For Kids Boy Girl Birthday Gift (60 Cm, Grey)",
    url: "https://m.media-amazon.com/images/I/715aY98VTPL._AC_UL480_FMwebp_QL65_.jpg",
    originalPrice: 30,
    salePrice: 20,
    rating: 5,
  },
  {
    id: 12,
    title: "La French Oudh Unisex Eau De Parfum Gift Set 4 x 20ml for Men & Women",
    url: "https://m.media-amazon.com/images/I/61m7HhVg2UL._SX522_PIbundle-4,TopRight,0,0_AA522SH20_.jpg",
    originalPrice: 30,
    salePrice: 12.95,
    rating: 4.5,
  },
];
